#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "ERROR: No arguments supplied"
    echo " "
    echo "INFO: Print active SNMP within a range using ping onesixtyone"
    echo "USAGE: Please enter ip range ex: 161-snmp-range-scan community 192.168.1 200 250"
    echo " "
fi
for ip in `seq ${3} ${4}`; do echo $2.$ip;done > ips
	onesixtyone -c $1 -i ips
rm ips
