#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "ERROR: No arguments supplied"
    echo " "
    echo "INFO: webcrawl a site and prints outs all the urls associated "
    echo "USAGE: please enter a domain ex. google.com"
    echo " "
fi
if [ $1 = "-f" ]
 then
   # Download landing page
   wget --no-check-certificate -np -N -nd -t1 -A.html -r -p -U Mozilla $2 -P ./tmp/ > /dev/null 2>&1
   grep -o 'href=".*:\/\/[A-Za-z0-9_\.-]*\.*\/.*".*' ./tmp/* | cut -d'"' -f2 | sort -u
else
   wget --no-check-certificate -np -N -nd -t1 -A.html -r -p -U Mozilla $1 -P ./tmp/ > /dev/null 2>&1
   grep -o 'href=".*:\/\/[A-Za-z0-9_\.-]*\.*\/.*".*' ./tmp/* | cut -d'"' -f2 | cut -d "/" -f3 | sort -u
fi
#cleanup
rm -rf ./tmp/
