#!/bin/bash

# reset all counters and iptables rules
iptables -Z && iptables -F
# measure incoming traffic to $1
iptables -I INPUT 1 -s $1 -j ACCEPT
# measure outgoing traffic to $1
iptables -I OUTPUT 1 -d $1 -j ACCEPT
echo "iptables -vn -L to see stats"
