#!/bin/bash
    for i in `seq ${2} ${3}`
    do
        ping -c 1 ${1}.${i} | grep "bytes from" | cut -d" " -f 4 |cut -d":" -f1 &
        if [ $? -eq 0 ]; then
            echo "${1}.${i} responded."
        else
            echo "${1}.${i} did not respond."
        fi
    done
